/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#5e2100',
        'on-tertiary-fixed': '#360f00',
        'surface-container-lowest': '#ffffff',
        primary: '#07241a',
        'inverse-primary': '#aecebe',
        tertiary: '#3c1200',
        'inverse-surface': '#30312e',
        'outline-variant': '#c1c8c3',
        'surface-dim': '#dbdad6',
        'on-primary-fixed-variant': '#304c41',
        'on-surface-variant': '#424844',
        'secondary-container': '#c8ebd4',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        'surface-container-high': '#eae8e4',
        'primary-fixed-dim': '#aecebe',
        secondary: '#466553',
        'primary-fixed': '#caeada',
        'surface-container-low': '#f5f3ef',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#accfb9',
        'tertiary-fixed-dim': '#ffb595',
        'on-primary-container': '#86a496',
        'on-secondary-fixed': '#022113',
        'on-tertiary-fixed-variant': '#76330f',
        outline: '#727974',
        'on-tertiary-container': '#e1855b',
        'surface-container-highest': '#e4e2de',
        'on-background': '#1b1c1a',
        'primary-container': '#1e3a2f',
        surface: '#fbf9f5',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#ffdbcd',
        'on-secondary-fixed-variant': '#2f4d3c',
        'on-secondary-container': '#4c6b59',
        error: '#ba1a1a',
        'inverse-on-surface': '#f2f0ed',
        'surface-tint': '#486458',
        'secondary-fixed': '#c8ebd4',
        'surface-variant': '#e4e2de',
        'on-primary-fixed': '#032017',
        'error-container': '#ffdad6',
        'surface-bright': '#fbf9f5',
        'on-error-container': '#93000a',
        'on-surface': '#1b1c1a',
        'surface-container': '#efeeea',
        background: '#fbf9f5',
        'terracotta': '#c26d45',
        'terracotta-hover': '#a85a34',
        'brass': '#b89758',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4rem',
        'space-4xl': '6rem',
        'gutter-mobile': '1rem',
        'gutter-tablet': '1.5rem',
        'gutter-desktop': '2rem',
        'container-max': '1280px',
      },
      fontFamily: {
        display: ['"Playfair Display"', 'serif'],
        body: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'display-lg-mobile': ['38px', { lineHeight: '46px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['30px', { lineHeight: '38px', letterSpacing: '0em', fontWeight: '600' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '0em', fontWeight: '500' }],
        'headline-sm': ['22px', { lineHeight: '30px', letterSpacing: '0.005em', fontWeight: '600' }],
        'subheading-lg': ['18px', { lineHeight: '26px', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', letterSpacing: '0.005em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.04em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.06em', fontWeight: '600' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
